GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "hooha ejeha",
    "author": "haha",
    "url": "meow.com",
    "likes": 2
}

###
PUT http://localhost:3003/api/blogs/65fddcf474afa8791bf66c44 HTTP/1.1
content-type: application/json

{
    "title": "hooha HA",
    "author": "haha",
    "url": "meow.com",
    "likes": 2
}

###
DELETE http://localhost:3003/api/blogs/65fddd8474afa8791bf66c50 HTTP/1.1
